name: mock_backend
description: A mock of a sample backend that uses Hive to store data
version: 1.0.0

environment:
  sdk: ^3.4.3

dependencies:
  mocktail: ^1.0.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.5.0+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
